version: "3"
services: 
  node-app:
    build: .
    ports: 
      - "3001:3000"
    volumes:
      - "./:/app"
    # depends_on: 
    #   - mongo 

  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mac
      MONGO_INITDB_ROOT_PASSWORD: password 
    volumes: 
      - mongodb-volume:/data/db

volumes: 
  mongodb-volume:
